apiVersion: apps/v1
kind: Deployment
metadata: 
  name: go-backend-deployment
  labels:
    app: go-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name:  go-backend
          image: fmelihh/go-backend
          ports:
            - containerPort: 8000
            
---

apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
spec:
  selector:
   app: go-backend
  type: LoadBalancer
  ports:
    - port:  8000
      targetPort: 8000
      protocol: TCP

